include:
  project: 'quintolin/config-ci'
  file: '.gitlab/lint.yml'
  ref: 'main'

lint-editorconfig:
  extends: '.lint-editorconfig'

lint-php-coding-style:
  extends: '.lint-php-coding-style'

lint-composer-json-file:
  extends: '.lint-composer-json-file'
